name: Go tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  gotests:
    runs-on: ubuntu-latest
    name: Go tests
    container: registry.access.redhat.com/ubi9/go-toolset:latest
    steps:
      - uses: actions/checkout@v5
      - name: Add Go bin to PATH
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Unit tests
        run: make unit_tests
      - name: Check code coverage
        run: ./check_coverage.sh
